In [3]:
#Q1a
import numpy as np
counter = np.arange (-15,16,1)
print(counter)
print(counter.shape)

[-15 -14 -13 -12 -11 -10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2
   3   4   5   6   7   8   9  10  11  12  13  14  15]
(31,)


In [12]:
#Q1b
even = np.arange(10,102,2)
print(even)
print(even.shape)

[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]
(46,)


In [14]:
#Q1c
backcounter = np.arange(1000,98,-50)
print(backcounter)
print(backcounter.shape)

[1000  950  900  850  800  750  700  650  600  550  500  450  400  350  300
  250  200  150  100]
(19,)


In [25]:
#Q1d
N = 3
a = np.arange(1, 20, 0.25)
b = np.array(a*a)
c = np.sqrt(a)
print(a)
print(b)
print(c)

[  1.     1.25   1.5    1.75   2.     2.25   2.5    2.75   3.     3.25
   3.5    3.75   4.     4.25   4.5    4.75   5.     5.25   5.5    5.75   6.
   6.25   6.5    6.75   7.     7.25   7.5    7.75   8.     8.25   8.5
   8.75   9.     9.25   9.5    9.75  10.    10.25  10.5   10.75  11.    11.25
  11.5   11.75  12.    12.25  12.5   12.75  13.    13.25  13.5   13.75  14.
  14.25  14.5   14.75  15.    15.25  15.5   15.75  16.    16.25  16.5
  16.75  17.    17.25  17.5   17.75  18.    18.25  18.5   18.75  19.    19.25
  19.5   19.75]
[   1.        1.5625    2.25      3.0625    4.        5.0625    6.25
    7.5625    9.       10.5625   12.25     14.0625   16.       18.0625
   20.25     22.5625   25.       27.5625   30.25     33.0625   36.
   39.0625   42.25     45.5625   49.       52.5625   56.25     60.0625
   64.       68.0625   72.25     76.5625   81.       85.5625   90.25
   95.0625  100.      105.0625  110.25    115.5625  121.      126.5625
  132.25    138.0625  144.      150.0625  156.2

In [49]:
squares = np.vstack([a, b, c])
squares = np.transpose([a, b, c])
print(squares[:5])
print(squares.shape)
print(squares.size)

[[ 1.          1.          1.        ]
 [ 1.25        1.5625      1.11803399]
 [ 1.5         2.25        1.22474487]
 [ 1.75        3.0625      1.32287566]
 [ 2.          4.          1.41421356]]
(76, 3)
228


In [63]:
#Q1e
print(squares[12,1])
print(squares[26,])
print(squares[75,])

16.0
[  7.5         56.25         2.73861279]
[  19.75        390.0625        4.44409721]


In [75]:
#Q2a
import numpy as np
a = np.arange(3,20,1)
product = 1
for x in a:
    product = product * x
print(product)

60822550204416000


In [88]:
#Q2b
b = np.arange(1,201,1)
count = 0
for x in b:
    if (x%17==0):
        count = count + 1
print(count)

11


In [98]:
#Q3a
import random
coin1time = np.random.randint(0, 2, 1)
b = 0
for x in coin1time:
    if x==0:
        b = b+1
if b==1:
    print("tail")
if b==0:
    print("head")

head


In [106]:
#Q3b
coin10time = np.random.randint(0, 2, 10)
count = 0
for y in coin10time:
    if y==0:
        count = count + 1
print(count)

7


In [107]:
#Q3c
coin3time = np.random.randint(0,2,3)
headcount = 0
for z in coin3time:
    if z==0:
        headcount = headcount + 1
if headcount<1:
    print("no")
if headcount>=1:
    print("yes")

yes


In [28]:
#Q3d
coin3time = np.random.randint(0, 2, 3)
headcount=0
trailcount=0
for headcount in range (0,100):    
    for x in range (0,3):
        x = np.random.randint(0,2)
        if x==0:
            headcount = headcount + 1
    if headcount>=1:    
        trailcount = trailcount + 1   
    headcount = 0
fraction = trailcount/100 
print(fraction)
# I know the fraction cannot be 1.0
# I tried to make the number through the loop to get the headcounts in each trail, and through the second loop to get the trailcounts.
# I do not know where the mistakes are.

1.0
100


In [20]:
#Q4
#I would like to learn to use computational tools to analyze scientific data. I prefer to learn more about the some specific tools that commonly used for biological studies.

In [ ]:
#Q5
#Around 3 hours. I should be need more time if I did this alone.